StartupEvents.postInit((event) => {
	let material = new NebulaMaterial("abc")

	material.create("test", BlockTags.NEEDS_STONE_TOOL)
		.color(0xB87333, 0xD4956A)
		.destroy(3, 6)
		.isMetal()
		.ingot()
		.nugget()
		.plate()
		.dust()
		.rod()
		.gear()
		.wire()
		.rawOre()
		.metalBlock()
		.rawBlock()
		.molten()
})